create table if not exists mold_storage_location (
    location_code varchar(64) primary key,
    location_name varchar(160) not null,
    capacity integer not null default 1,
    active boolean not null default true,
    created_by varchar(64) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

insert into mold_storage_location (location_code, location_name, capacity, active, created_by, created_at, updated_at) values
('MOLD-A-01', 'A区-01', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-A-02', 'A区-02', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-A-03', 'A区-03', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-A-04', 'A区-04', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-A-05', 'A区-05', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-A-06', 'A区-06', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-A-07', 'A区-07', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-A-08', 'A区-08', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-01', 'B区-01', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-02', 'B区-02', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-03', 'B区-03', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-04', 'B区-04', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-05', 'B区-05', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-06', 'B区-06', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-07', 'B区-07', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-B-08', 'B区-08', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-01', 'C区-01', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-02', 'C区-02', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-03', 'C区-03', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-04', 'C区-04', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-05', 'C区-05', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-06', 'C区-06', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-07', 'C区-07', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-C-08', 'C区-08', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-01', 'D区-01', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-02', 'D区-02', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-03', 'D区-03', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-04', 'D区-04', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-05', 'D区-05', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-06', 'D区-06', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-07', 'D区-07', 1, true, 'SYSTEM', current_timestamp, current_timestamp),
('MOLD-D-08', 'D区-08', 1, true, 'SYSTEM', current_timestamp, current_timestamp)
on conflict do nothing;
