spring.flyway.locations=classpath:db/postgresql
spring.flyway.ignore-migration-patterns=
spring.datasource.url=${MES_DATABASE_URL}
spring.datasource.username=${MES_DATABASE_USERNAME}
spring.datasource.password=${MES_DATABASE_PASSWORD}
